spring:
  application:
    name: consumer
  profiles:
    include: dev
  rabbitmq:
    host: 127.0.0.1
server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
test: xiayin-dev-test-1
