spring:
  application:
    name: @artifactId@
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
        shared-configs[x]: application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

server:
  port: 9090