management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: user
  rabbitmq:
    host: 39.104.97.83
    port: 5672
    username: admin
    password: 5555
    listener:
      simple:
        #人为地获取到channel之后调用方法向server发送ack（或消费失败时的nack）信息
        acknowledge-mode: manual
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
security:
  oauth2:
    resource:
      id: user
      user-info-uri: http://localhost:2222/auth-server/user
      prefer-token-info: false