spring:
  application:
    name: auth-server
  redis:
    host: 39.104.97.83
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
##数据库配置
hikaricp:
  dataSource:
    jdbc:
      driverClassName: com.mysql.cj.jdbc.Driver
    connectionTestQuery: SELECT 1
    connectionTimeout: 9000
    idleTimeout: 45000
    maxLifetime: 50000
    maximumPoolSize: 10
    minimumIdle: 5
    url: jdbc:mysql://127.0.0.1:3306/xiayin?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 12345
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

