management:
  endpoint:
    health:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback
        - id: auth_route
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback
        - id: requestratelimiter_route
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 1
      enabled: true
      discovery:
        locator:
          #表示gateway开启服务注册和发现功能,
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #表示将请求路径的服务名配置改成小写  因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true
  redis:
    host: 39.104.97.83
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
security:
  oauth2:
    client:
      client-id: webapp
      access-token-uri: http://localhost:8888/auth-server/oauth/token
      user-authorization-uri: http://localhost:8888/auth-server/oauth/authorize
    resource:
      user-info-uri: http://localhost:8888/auth-server/user
      prefer-token-info: false
logging.level:
  org.springframework.security: DEBUG
  org.springframework.gateway: DEBUG



