management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    include: local
  application:
    name: eureka-v1-00
  mvc:
    locale: zh_CN
  http:
    encoding:
      enabled: true
      force: true
server:
  port: 8761
  connectionTimeout: 30000
  tomcat:
    basedir: ./tmp
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
    maxThreads: 100
    minSpareThreads: 20
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
