management:
  endpoint:
    health:
      enabled: false
spring:
  profiles:
    include: local
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiayin01/config
server:
  port: 8889
  connectionTimeout: 30000
  tomcat:
    basedir: ./tmp
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
    maxThreads: 100
    minSpareThreads: 20
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #注册到 Eureka Server ,并被其他服务发现
    register-with-eureka: true
    #客户端是否从 Eureka Server 获取实例注册信息
    fetch-registry: true
  instance:
    #以IP形式注册
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}